### ISSUE TITLE
Missing genome file documentation

### ISSUE THREAD

**Issue by rubens21** [yaricom/goNEAT#22]
hi @yaricom ,

I am trying to use this lib, but I did not find a documentation about how the genoma file is created.
I could guess some columns meaning, but not all of them.

Could we have short description of each column? 

Thank you

**Comment by yaricom** [comment]
Hello @rubens21,

The library now supports two formats of genome file: plain text and yaml. The former is a bit outdated right now, however it is more concise. While the YAML format is more self descriptive. 

Please take a look at [test_seed_genome.yml](https://github.com/yaricom/goNEAT/blob/master/data/test_seed_genome.yml)

Let me know if this helped you.

Thank you,
Iaroslav

**Comment by rubens21** [comment]
Thank @yaricom,

That file is much easier to understand.
Are _traits_ a NEAT thing or is it something particular to your project? Sorry, I am not familiar with NEAT yet. I just started to study it.

**Comment by yaricom** [comment]
Hello @rubens21,

The **traits** are the part of the NEAT algorithm. It is individual features of organisms which can mutate during the evolution. You can ignore it as for now as **traits** have no influence on reproduction.

Iaroslav

**Comment by rubens21** [comment]
Thank you a lot for your answers and for publishing this project.
I will continue to read about NEAT.
:-)
